# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170325_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_date',
            new_name='date_of_death',
        ),
    ]
