# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170326_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstances',
            new_name='BookInstance',
        ),
    ]
